require("symbols-outline").setup(
  {
    highlight_hovered_item = true,
    show_guides = true,
    auto_preview = false,
    position = 'right',
    relative_width = true,
    width = 25,
    auto_close = false,
    show_numbers = false,
    show_relative_numbers = false,
    show_symbol_details = true,
    preview_bg_highlight = 'Pmenu',
    autofold_depth = nil,
    auto_unfold_hover = true,
    fold_markers = { '', '' },
    wrap = false,
    keymaps = { -- These keymaps can be a string or a table for multiple keys
      close = { "<Esc>", "q" },
      goto_location = "<Cr>",
      focus_location = "o",
      hover_symbol = "gh",
      toggle_preview = "<c-h>",
      rename_symbol = "r",
      code_actions = "a",
      fold = "i",
      unfold = "h",
      fold_all = "H",
      unfold_all = "I",
      fold_reset = "R",
    },
    lsp_blacklist = {},
    symbol_blacklist = {},
    symbols = {
      File = { icon = "", hl = "@text.uri" },
      Module = { icon = "", hl = "@namespace" },
      Namespace = { icon = "", hl = "@namespace" },
      Package = { icon = "", hl = "@namespace" },
      Class = { icon = "𝓒 ", hl = "@type" },
      Method = { icon = "󰊕", hl = "@method" },
      Property = { icon = "", hl = "@method" },
      Field = { icon = " ", hl = "@field" },
      Constructor = { icon = "", hl = "@constructor" },
      Enum = { icon = "𝔼", hl = "@type" },
      Interface = { icon = "", hl = "@type" },
      Function = { icon = "ƒ", hl = "@function" },
      Variable = { icon = "", hl = "@constant" },
      Constant = { icon = "", hl = "@constant" },
      String = { icon = "", hl = "@string" },
      Number = { icon = "#", hl = "@number" },
      Boolean = { icon = "", hl = "@boolean" },
      Array = { icon = "", hl = "@constant" },
      Object = { icon = "𝕆", hl = "@type" },
      Key = { icon = "", hl = "@type" },
      Null = { icon = "󰟢", hl = "@type" },
      EnumMember = { icon = "", hl = "@field" },
      Struct = { icon = "𝕊", hl = "@type" },
      Event = { icon = "", hl = "@type" },
      Operator = { icon = "+", hl = "@operator" },
      TypeParameter = { icon = "𝙏", hl = "@parameter" },
      Component = { icon = "󰅴", hl = "@function" },
      Fragment = { icon = "󰅴", hl = "@constant" },
    },
  })
