#!/bin/sh

value=$()
if [[ "$1" == "--value" ]]; then
    if [ $value -gt 100 ]; then
        echo "100"
    else
      printf "%3d\n" $value
    fi
elif [[ "$1" == "--icon" ]]; then
    if [ $value -lt 10 ]; then
        echo " 󱩎"
    elif [ $value -lt 20 ]; then
        echo " 󱩏"
    elif [ $value -lt 30 ]; then
        echo " 󱩐"
    elif [ $value -lt 40 ]; then
        echo " 󱩑"
    elif [ $value -lt 50 ]; then
        echo " 󱩒"
    elif [ $value -lt 60 ]; then
        echo " 󱩓"
    elif [ $value -lt 70 ]; then
        echo " 󱩔"
    elif [ $value -lt 80 ]; then
        echo " 󱩕"
    elif [ $value -lt 90 ]; then
        echo " 󱩖"
    elif [ $value -le 100 ]; then
        echo " 󰛨"
    else
        echo "Error"
    fi
fi
