# NOTE: need to be enabled interception tools (service (systemctl enable udevmon))
- JOB: intercept -g $DEVNODE | caps2esc | dual-function-keys -c /home/anon/.config/interception/dual_function_key_conf.yaml | uinput -d $DEVNODE
  DEVICE:
    NAME: "AT Translated Set 2 keyboard"
