directory: ~/Documents/Music
library: ~/Documents/Music/Data/library.db
import:
    move: yes
plugins: chroma lyrics edit lastgenre smartplaylist mpdupdate
chroma:
    auto: yes
lyrics:
    auto: yes
lastgenre:
    count: 3
ignore:
    paths:
        - ~/Documents/Music/Need_Import
smartplaylist:
    relative_to: 
    playlist_dir: ~/Documents/Music/Playlists
    forward_slash: no
    playlists:
        - name: All.m3u
          query: ''
        - name: Disney.m3u
          query: 'genre:disney'
        - name: Jpop.m3u
          query: 'genre:"j-pop"'
        - name: Chanson.m3u
          query: 'genre:"chanson"'
        - name: Lana.m3u
          query: 'artist:"Lana Del Rey"'
        - name: Eminem.m3u
          query: 'artist:"eminem"'
