directory: ~/Documents/Music
library: ~/Documents/Music/Data/library.db
import:
    move: yes
plugins: chroma lyrics
chroma:
    auto: yes
lyrics:
    auto: yes
ignore:
    paths:
        - ~/Documents/Music/Need_Import
