# Sets user-defined palette
palette = "catppuccin_mocha"
add_newline = true

format = """
[ ](blue)\
$hostname\
$username\
$shell\
[](bg:lavender fg:blue)\
$directory\
[](fg:lavender bg:sky)\
$git_branch\
[](fg:sky bg:green)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:green bg:yellow)\
$docker_context\
[](fg:yellow bg:red)\
$time\
[ ](fg:red)\
"""

[line_break]
disabled = false

[palettes.catppuccin_latte]
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
text = "#4c4f69"
subtext0 = "#6c6f85"
subtext1 = "#5c5f77"
surface0 = "#ccd0da"
surface1 = "#bcc0cc"
surface2 = "#acb0be"
overlay0 = "#9ca0b0"
overlay1 = "#8c8fa1"
overlay2 = "#7c7f93"
blue = "#1e66f5"
lavender = "#7287fd"
sapphire = "#209fb5"
sky = "#04a5e5"
teal = "#179299"
green = "#40a02b"
yellow = "#df8e1d"
peach = "#fe640b"
maroon = "#e64553"
red = "#d20f39"
mauve = "#8839ef"
pink = "#ea76cb"
flamingo = "#dd7878"
rosewater = "#dc8a78"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

#$git_status\
# Disable the blank line at the start of the prompt

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:blue fg:base"
style_root = "bg:blue fg:base"
format = '[$user]($style)'

[hostname]
ssh_only = true
style = "bg:blue fg:base"
format = '[$ssh_symbol$hostname]($style) as '

[directory]
style = "bg:lavender fg:base"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:yellow fg:base"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:sky fg:base"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:sky fg:base"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:green fg:base"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = "bg:red fg:base"
format = '[ $time ]($style)'

[shell]
fish_indicator = '󰈺 '
bash_indicator = 'ᵦ'
zsh_indicator = 'ᶻ'
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = "bg:blue fg:base"
format = '[$indicator ]($style)'
disabled = false
