##################################################
#### Alacritty Configuration 
#### Terminal with vim like bindings
##################################################


##################################################
### Visual Config
##################################################

# Catppuccin theme for alacritty (I change this line with a script for ligth/dark mode switch)
[general]
import = ["/home/anon/.config/alacritty/catppuccin/catppuccin_mocha.toml"]
live_config_reload = true

[font]
size = 17.0
offset = {x = 0, y = 1}

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "bold italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "bold"

[window]
decorations = "full"
opacity = 0.9
padding = { x = 0, y = 0}

[scrolling]
# Maximum number of lines in the scrollback buffer.
history = 20000

[cursor]
style = {shape = "Block", blinking = "Never"}
vi_mode_style = {shape = "Block", blinking = "Never"}
thickness = 0.15

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift", mode = "Vi" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

# Hints for terminal prompt
[[hints.enabled]]
command = ""
action = "MoveViModeCursor"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "S", mods = "Shift", mode = "Vi" }
regex = "\\s"

[[hints.enabled]]
command = ""
action = "MoveViModeCursor"
persist = false
mouse.enabled = true
binding = { key = "a", mods = "Shift", mode = "Vi" }
regex = "a"

##################################################
### Mappings
##################################################

##############################
## Fix some bindings that don't work otherwise because of old reasons
##############################
[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[127;5u"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[91;5u"
key = "LBracket"
mods = "Control"


##############################
## Vi mode bindings
##############################
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "L"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "U"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "E"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "N"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "_"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = "$"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "E"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = 43
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "J"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = 97
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchNext"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "K"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchFocusNext"
key = "Return"
mode = "Search|~Vi"

[[keyboard.bindings]]
action = "SearchFocusPrevious"
key = "Return"
mode = "Search|~Vi"
mods = "Shift"

##############################
## Other bindings
##############################
[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "PageDown"
mods = "Control"
